apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ServerlessEventAppClaim
      name: messagewall
    patch: |
      - op: replace
        path: /metadata/name
        value: messagewall-dev-east
      - op: replace
        path: /spec/environment
        value: dev
      - op: replace
        path: /spec/region
        value: us-east-1
      - op: replace
        path: /spec/resourcePrefix
        value: messagewall-east
      - op: replace
        path: /spec/awsAccountId
        value: "205074708100"

labels:
  - pairs:
      environment: dev
      region: us-east-1
    includeSelectors: false
