apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - claim.yaml

# Common labels applied to all claims
labels:
  - pairs:
      app.kubernetes.io/part-of: messagewall
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
